### PR TITLE
Sorted

### PR DESCRIPTION
**Pull request by chriselrod**

### CODE REVIEW

**Comment by chriselrod** [comment]
I haven't looked at the `bracketstrictlymonotonic` yet; want me to SIMD it?

**Comment by ChrisRackauckas** [comment]
Yes, if that's possible that would be awesome. Then it might make sense to make use of it instead of https://github.com/SciML/OrdinaryDiffEq.jl/blob/master/src/dense/generic_dense.jl#L27-L55, which I forget what the origin of that search function was (@oscardssmith IIRC?)

**Comment by chriselrod** [comment]
`searchsortedfirst` does pretty well compared to the method I added here. I haven't tested it that much yet, but bisection is pretty good, so the wins from mixing it with a linear scan might be small.

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by ChrisRackauckas** [comment]
A SIMD bisection would be awesome for SimpleNonlinearSolve.jl I've considered it before, checking the j/(N+1) points instead of just 1/2 to subdivide quicker. Anyways, separate topic 😅

**Pull request merged**
